Render realisation, controller status, custom headers, 404, #show wit…
CepCap/simpler pull request #1
Opened 2019-03-09 23:58 UTC by CepCap

Final rails basics lesson

2019-03-10 22:42 UTC, psylone requested changes

2019-03-10 22:42 UTC, psylone commented on lib/simpler/controller.rb
> +      params[':id'] = @request.env[':id'] if @request.env[':id']
Если использовать строку в качестве ключа, то должно быть так: `params['id']`, если использовать символ, то так: `params[:id]`.

2019-03-10 22:42 UTC, psylone commented on lib/simpler/controller/custom_headers.rb
> +    @response[header] = value
Особого смысла в отдельном классе здесь нет. Достаточно это выражение сделать телом метода `custom_headers`. Или ещё проще:

```ruby
def headers
  @response
end
```

Поскольку `@response` реализует метод `[]=`, нам по сути ничего делать не нужно.

Либо сделать более явный интерфейс:

```ruby
def set_header(header, value)
  @response[header] = value
end
```

2019-03-10 22:42 UTC, psylone commented on lib/simpler/router.rb
> +      env[':id'] = path.match(/\d+/)[0] if path.match(/\/\d+/)
Роут параметров может быть несколько, они могут называться по-разному. Например:

```ruby
# Для роута
get '/tests/:test_id/questions/:id' => 'questions#show'

# Для такого URL
/tests/101/questions/23

# Мы должны получить хэш роут параметров
{ 'test_id' => '101', 'id' => '23' }
```

2019-03-10 22:42 UTC, psylone commented on lib/simpler/router.rb
>        @routes.find { |route| route.match?(method, path) }
Имеет смысл логику поиска и назначения роут параметров поместить в класс `Route` и сделать ридер `params`. Тогда здесь если роут будет найден, мы сможем установить хэш роут параметров в `env`:

```ruby
route = @routes.find { |route| route.match?(method, path) }

if route
  env['simpler.route_params'] = route.params
end
```

2019-03-10 22:42 UTC, psylone commented on lib/simpler/controller.rb
Также должен быть метод `params`, который вернёт хэш со всеми параметрами запроса: GET, POST и роут параметрами.

2019-03-10 22:42 UTC, psylone commented on lib/simpler/router/route.rb
> +          path.gsub!(/\d+/, ':id')
Не стоит модифицировать путь из `env`.

2019-03-10 22:42 UTC, psylone commented on lib/simpler/router/route.rb
> +          path.gsub!(/\d+/, ':id')
Также роут параметров может быть несколько и они могут иметь произвольные названия (которые мы определили в конфиге роутов).

2019-03-10 22:42 UTC, psylone commented on log/app.log
> +I, [2019-03-09T15:34:47.911405 #8564]  INFO -- :
Лог стоит исключить из репозитория.

2019-03-10 22:42 UTC, psylone commented on log/app.log
> +Request: GET /tests/:id
Здесь должен быть именно тот путь который запросил клиент.

2019-03-10 22:42 UTC, psylone commented on middleware/app_logger.rb
> +    if controller
👍

2019-03-10 22:42 UTC, psylone commented on app/controllers/tests_controller.rb
> +    render plain: 'tests/list'
Суть `plain` в том чтобы отрендерить произвольный текст, например: `render plain: 'The quick brown fox jumps over the lazy dog'`.

2019-03-13 09:56 UTC, BubuntuClu commented on log/app.log
> +I, [2019-03-11T17:29:22.894020 #3040]  INFO -- :
лог так и не исключен

2019-03-13 09:56 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    @id = params[':id']
почему такое странное обращение? `:id`/`'id'`

2019-03-13 12:44 UTC, CepCap commented on log/app.log
> +I, [2019-03-11T17:29:22.894020 #3040]  INFO -- :
странно, в гитигнор вроде добавил папку лог и все в ней

2019-03-13 22:32 UTC, psylone approved these changes

2019-03-13 22:32 UTC, psylone commented on lib/simpler/controller.rb
> +    def get_params
По сути, мы наоборот устанавливаем здесь параметры, поэтому лучше назвать `set_params` или `set_extra_params`.

2019-03-13 22:32 UTC, psylone commented on lib/simpler/controller.rb
> +      end
`@request.params.merge!(@request.env['simpler.params'])`.

2019-03-13 22:32 UTC, psylone commented on lib/simpler/controller.rb
> +        @response.write(template[:plain])
Предполагается что содержимое ответа записывается в единственном месте (в нашем случае в методе `write_response`). Если логика записи содержимого ответа будет расползаться, это может вызвать трудности в поддержке и расширении кода.

Рендеринг содержимого ответа различных типов стоит делать в представлении. Например, для каждого типа ответа может быть свой класс рендерер: `HTMLRenderer`, `PlainRenderer`, `JSONRenderer`, который будет определять метод `render`. Тогда в обязанности `View` будет входить выбор нужного класса рендерера и делегирование ему метода `render`.

2019-03-13 22:32 UTC, psylone commented on lib/simpler/router/route.rb
> +        values = path.scan(/\/(\d+)\/?/).flatten
Значение роут параметров не обязательно числовые. Это может быть произвольная строка.

2019-03-13 22:32 UTC, psylone commented on lib/simpler/router/route.rb
> +          route_path = path.gsub(/\/(\d+)\/?/, '/:id')
Роут параметр может называться произвольным образом, например: `/tests/:test_id/questions/:id`.

2019-07-05 09:33 UTC, closed without merging